image: ubuntu:latest

default:
  before_script:
    - apt-get update -yqq
    - apt-get install -y nodejs
    - apt-get install -y npm

stages:
  - install
  - audit
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
      expire_in: 30 mins
      paths:
        - ./frontend/.npm/
        - ./frontend/node_modules/

audit:
    stage: audit
    script:
        - npm audit


build:
  stage: build
  script:
    - |
      {
        npm run build &&
        echo "Successfully built frontend."
      } || {
        echo "Something went wrong while building frontend."
      }
  only:
    - master

test:
  stage: test
  script:
    - echo "Running frontend tests."
    - npm test
    
deploy:
  stage: deploy
  script:
    - echo "Deploy frontend here..."
  only:
    - master
