image: node:latest

stages:
  - install
  - audit
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - npm install

audit:
    stage: audit
    script:
        - npm audit


build:
  stage: build
  script:
    - |
      {
        npm build &&
        echo "Successfully built frontend."
      } || {
        echo "Something went wrong while building frontend."
      }
    only:
      - master

test:
  stage: test
  script:
    - echo "Running frontend tests."
    - npm test