image: ubuntu:latest

default:
  before_script:
    - apt-get update -yqq
    - apt-get install -y nodejs
    - apt-get install -y npm

stages:
  - install
  - audit
  - build
  - test
  - deploy

install:
  stage: install
  script:
    - cd frontend/
    - npm install
    - npm audit
  artifacts:
      expire_in: 30 mins
      paths:
        - ./.npm/
        - ./node_modules/

build:
  stage: build
  script:
    - cd frontend/
    - |
      {
        npm run build &&
        echo "Successfully built frontend."
      } || {
        echo "Something went wrong while building frontend."
      }
  only:
    - master

test:
  stage: test
  script:
    - cd frontend/
    - echo "Running frontend tests."
    - npm test
    
deploy:
  stage: deploy
  script:
    - cd frontend/
    - echo "Deploy frontend here..."
  only:
    - master
