stages:
  - audit
  - install
  - build
  - test
  - deploy

default:
  image: node:latest

audit:
    stage: audit
    script:
        - npm audit


install:
  stage: install
  needs: [audit]
  script:
    - npm install

build:
  stage: build
  needs: [install]
  script:
    - |
      {
        npm build &&
        echo "Successfully built frontend."
      } || {
        echo "Something went wrong while building frontend."
      }
    only:
      - master

test:
  stage: test
  needs: [build]
  script:
    - echo "Running frontend tests."
    - npm test