stages:
  - audit
  - install
  - linting
  - test
  - staging
  - deploy

default:
  image: node:latest

audit:
    stage: audit
    script:
        - npm audit

install:
  stage: install
  needs: [audit]
  script:
    - npm install

linting:
  stage: linting
  script:
    - npm run lint

test:
  stage: test
  needs: [install]
  script:
    - echo "Running backend tests."
    - npm test

staging:
  type: deploy
  stage: staging
  image: node:latest
  script:
    - echo "Running staging stage."
  only:
    - develop

deploy:
  type: deploy
  stage: deploy
  image: node:latest
  script:
    - echo "Running deploy stage."
  only:
    - master