image: ubuntu:latest

default:
  before_script:
    - cd /backend
    - apt-get update -yqq
    - apt-get install -y nodejs
    - apt-get install -y npm

stages:
  - install
  - audit
  - linting
  - test
  - staging
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
      expire_in: 30 mins
      paths:
        - .npm/
        - node_modules/

audit:
    stage: audit
    script:
        - npm audit

linting:
  stage: linting
  script:
    - npm run lint

test:
  stage: test
  script:
    - echo "Running backend tests."
    - npm test

staging:
  type: deploy
  stage: staging
  image: ubuntu:latest
  script:
    - echo "Running staging stage."
  only:
    - develop

deploy:
  type: deploy
  stage: deploy
  image: ubuntu:latest
  script:
    - echo "Running deploy stage."
  only:
    - master