name: Github CI

on:
  push:
    branches: [develop, master]

jobs:
  backend-test:

    runs-on: ubuntu-latest

    environment: testEnvironment

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Backend install and test
      env:
        EMAIL_SERVICE_NAME: ${{ secrets.EMAIL_SERVICE_NAME }}
        EMAIL_SERVICE_HOST: ${{ secrets.EMAIL_SERVICE_HOST }}
        EMAIL_SERVICE_SECURE: ${{ secrets.EMAIL_SERVICE_SECURE }}
        EMAIL_SERVICE_PORT: ${{ secrets.EMAIL_SERVICE_PORT }}
        DEV_EMAIL_USER_NAME: ${{ secrets.DEV_EMAIL_USER_NAME }}
        DEV_EMAIL_PASSWORD: ${{ secrets.DEV_EMAIL_PASSWORD }}
        DB_PASSPHRASE: ${{ secrets.DB_PASSPHRASE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_TEST_CONNECTION_STRING: ${{ secrets.DB_TEST_CONNECTION_STRING }}
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        TOKEN_ALGORITHM: ${{ secrets.TOKEN_ALGORITHM }}
        TEST_PORT: ${{ secrets.TEST_PORT }}
        PORT: ${{ secrets.PORT }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        cd backend/
        npm install
        npm run test:pipeline

  frontend-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Frontend install and build
      run: |
        cd frontend/
        npm install
        npm run build

#  deploy:
#   needs: [test]
#   runs-on: ubuntu-latest
#
#   steps:
#   - name: SSH and deploy node app
#     uses: appleboy/ssh-action@master
#     with:
#       host: ${{ secrets.SSH_HOST }}
#       username: ${{ secrets.SSH_USERNAME }}
#       key: ${{ secrets.SSH_KEY }}
#       port: ${{ secrets.SSH_PORT }}
#       script: |
#         cd ~/node-github-demo
#         git pull origin master
#         npm install --production
#         pm2 restart node-app
